# Generated by Django 6.0.3 on 2026-04-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней активности'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='streak_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ударная серия'),
        ),
    ]
