# Generated by Django 6.0.3 on 2026-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_last_activity_date_myuser_streak_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_activity_date',
            field=models.DateField(default='1900-1-1', verbose_name='Дата последней активности'),
        ),
    ]
