# Generated by Django 6.0.3 on 2026-03-28 14:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='picture',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
