# Generated by Django 6.0.3 on 2026-03-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order_num',
            field=models.PositiveBigIntegerField(),
        ),
    ]
