# Generated by Django 6.0.3 on 2026-03-28 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order_num',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
